<script type="text/javascript">
  $jq(function() {
    varienGlobalEvents.attachEventHandler('showTab', function(e) {
      var $chartContainer = $jq("#rmz-chart-<?php echo $this->getData('chart_id'); ?>");

      if (e.tab &&
          $jq(e.tab).is('#diagram_tab_<?php echo $this->getData("chart_id"); ?>') &&
          !$chartContainer.children('iframe').length) {

        var _baseUrl = "https://<?php echo Mage::helper('reamaze_reamaze')->getAccountName()?>.<?php echo Mage::helper('reamaze_reamaze')->getDomain(); ?>";
        var _user = {
          "id": "<?php echo Mage::getSingleton('admin/session')->getUser()->getId(); ?>",
          "authkey": "<?php echo Mage::helper('reamaze_reamaze')->getAuthKey(Mage::getSingleton('admin/session')->getUser()->getId()); ?>",
          "parent_url": window.location.href
        };

        var url = _baseUrl + '/admin/reports/<?php echo $this->getData("chart_id"); ?>' + '?' + $jq.param({sso: _user, widget: 1, app: 'magento'});
        var embedEle = $jq('<iframe/>').attr({width: "100%", src: url, scrolling: "no", frameborder: "0", allowtransparency: "true", name: "_widget_chart_" + '<?php echo $this->getData("chart_id"); ?>'});
        $chartContainer.html(embedEle);

        $jq.receiveMessage(function(e) {
          var msgAr = $jq.deparam(e.data);
          var frame = $jq('iframe[name="' + msgAr._name + '"]');
          if (frame.length) {
            frame.height(msgAr._height);
          }
        }, _baseUrl);
      }
    });
  });
</script>

<div id="rmz-chart-<?php echo $this->getData('chart_id'); ?>"></div>