<script type="text/javascript">
  $jq(function() {
    var _baseUrl = "https://<?php echo Mage::helper('reamaze_reamaze')->getAccountName()?>.<?php echo Mage::helper('reamaze_reamaze')->getDomain(); ?>";
    var _user = {
      "id": "<?php echo Mage::getSingleton('admin/session')->getUser()->getId(); ?>",
      "email": "<?php echo Mage::getSingleton('admin/session')->getUser()->getEmail(); ?>",
      "authkey": "<?php echo Mage::helper('reamaze_reamaze')->getAuthKey(Mage::getSingleton('admin/session')->getUser()->getId(), Mage::getSingleton('admin/session')->getUser()->getEmail()); ?>",
      "parent_url": window.location.href
    };

    var url = _baseUrl + '/admin/<?php echo $this->getData("actionPath"); ?>?' + $jq.param({sso: _user, framed: 1, app: 'magento'});
    var embedEle = $jq('<iframe/>').attr({style: "min-height: 400px;", width: "100%", src: url, scrolling: "no", frameborder: "0", allowtransparency: "true", name: "_embed"});
    $jq("#reamaze-dashboard").append(embedEle);

    $jq.receiveMessage(function(e) {
      var msgAr = $jq.deparam(e.data);
      var frame = $jq('iframe[name="' + msgAr._name + '"]');
      if (frame.length) {
        frame.height(msgAr._height);
      }
    }, _baseUrl);
  });
</script>

<div id="reamaze-dashboard"></div>